### ISSUE TITLE
Ensure that repository settings are properly configured

### ISSUE THREAD

**Issue by jwaggs** [ascmitc/mhl#1]
Before beginning the mhl implementation, we need to formalize the pull-request process, determine our branching scheme and protection rules, etc. Here are some basic questions to address....

1. How many reviews are required for a pull request to be approved?

2. Which collaborators are allowed and/or expected to review/approve/merge pull requests?

3. Shall we formalize any branches other than the main branch? i.e. do we want a staging branch for beta purposes?

The list goes on, but this is a good place to hash out some of these early details. Let's keep track of our initial repository rules, details and configuration here.

**Comment by ptrpfn** [comment]
IMHO such processes depend on how we intend to use the repository in the future. If it is going to evolve into reference implementation that is a well tested and that can be used in production, I totally agree that we need good rules for maintaining the repository. If it's more of a playground (what it is right now) that goes along the last rounds of iterating the specification in our meetings, I think a strict process will not be that essential. So I guess these are good questions for the next Data Management meeting.

**Comment by jwaggs** [comment]
I can get behind that. When I initially opened this issue no code had been committed to the repository yet. I usually like to make a point to ensure all code is properly reviewed by at least one maintainer out of principle, even if the code is submitted by another maintainer. Obviously I'll still go back and review everything you committed the other day and I can simply open issues and / or pull requests as necessary.

That being said, moving forward I think it would be good if you and I got in the habit of formally reviewing each-other's code via a PR... even if it's only you and I really working on it at this point. I agree we don't need to get more specific than that right now though.

I'll be in touch, but I'm quite booked until mid September with existing work obligations and upcoming vacations. I don't expect to be able to truly review your commit and then add my own work until then.

**Comment by ptrpfn** [comment]
That sounds good. There won't be too much activity from our side either before the next meeting. From there we should be able to see what the next tasks for this repository will be.

**Comment by jwaggs** [comment]
I will do this once assigned the proper admin permissions.

**Comment by jwaggs** [comment]
The master branch now has a protection rule enforcing that pull requests must be approved by at least one reviewer. This protection rule is applied to even admins. No branch other than master branch is currently protected. As the project progresses, if a more formal branching scheme becomes necessary, then those branches can be protected at such time. This closes the initial scope of the issue.
