### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by jwaggs** [ascmitc/mhl#11]
Currently, all testing is simulated via the `Scenarios/_test_all.sh` script, and visually parsing the details for anomalies in a git diff.

While the `_create_readme.sh` and `_test_all.sh` scripts are valuable to quickly showcase desired functionality, they should not be used as an authoritative source regarding the functional integrity of the system. We should refactor the unit testing to a utilize an actual python testing framework so that test output and failures become more clear, and so that pipelines can be set up to auto test branches before allowing them to be merged into master.

**Comment by jwaggs** [comment]
I will get the initial project testing structure setup and then patrick will translate his existing scenarios into python tests.

**Comment by ptrpfn** [comment]
Additional thought: Besides unit tests also define end-to-end tests that could be adapted by 3rd party implementors of ASC-MHL?

**Comment by jwaggs** [comment]
I've created PR #20 to start staging our testing development. 

See the updated README for the tests info. I went with pytest.

**Comment by jwaggs** [comment]
This has progressed enough to close
