### ISSUE TITLE
AttributeError: 'NaturalOrderGroup' object has no attribute 'resultcallback'

### ISSUE THREAD

**Issue by akda5id** [ascmitc/mhl#127]
```
# ascmhl --version
  Traceback (most recent call last):
  File "/usr/local/bin/ascmhl", line 5, in <module>
    from ascmhl.cli.ascmhl import mhltool_cli
  File "/usr/local/lib/python3.8/site-packages/ascmhl/cli/ascmhl.py", line 30, in <module>
    @mhltool_cli.resultcallback()
  AttributeError: 'NaturalOrderGroup' object has no attribute 'resultcallback'
```

Python 3.8.13 on freebsd 13.0-RELEASE-p11. Installed from pip (ascmhl-0.9-py3-none-any.whl).
Let me know if there is any further info you need to track this down, happy to help out.

**Comment by llamafilm** [comment]
Exact same problem here on a fresh install of macOS 12.3.  My install went like this:

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install fio # this gets Xcode tools installed
pip3 install --upgrade ascmhl
export PATH=~/Library/Python/3.8/bin/:$PATH
```

**Comment by hjmallon** [comment]
`resultcallback` should have an underscore - `result_callback`. At least that fixes it for me.

**Comment by llamafilm** [comment]
Thanks @hjmallon!  I found some context at https://github.com/pallets/click/pull/1848

**Comment by llamafilm** [comment]
This problem happens if you run a newer version of `Click`.  Even though the requirements.txt specifies `Click==7.0`, for some reason `pip install ascmhl` gives me version 8.1 instead.  I don't understand why.

**Comment by hjmallon** [comment]
Setup.py has ‘Click>=7.0’ which is what pip will read

**Comment by ptrpfn** [comment]
Fixed with release https://github.com/ascmitc/mhl/releases/tag/v0.9.1
