### ISSUE TITLE
 ascmhl create -> ERR: fixme: non-c4 hash in chain file, not implemented

### ISSUE THREAD

**Issue by SiDu1860** [ascmitc/mhl#136]
Hi,

tested the ascmhl create function and there was an error in terminal though there was created a new mhl entry in the ascmhl_chain.xml and there was also placed a new "0002_(...).mhl" file in the ascmhl subfolder. 

<img width="1221" alt="Screenshot 2023-03-27 at 14 04 08" src="https://user-images.githubusercontent.com/36437904/227937380-37eae4f0-d262-45e0-9aba-a967fc0351fb.png">

<img width="735" alt="Screenshot 2023-03-27 at 14 07 49" src="https://user-images.githubusercontent.com/36437904/227937395-0eaa5814-deb9-4c91-9241-38ee7406c1c6.png">

Do:
- create HDE files with new version of ARRI HDE Transcoder 1.4.0.10577
- verify files with 'ascmhl-debug verify' command
- add new files to subfolder containing files
- do 'ascmhl create' command

Happen: 
- 'ascmhl_chain.xml' was updated
- new 'mhl' checksum file incl. the file was generated
- but terminal outputs an error 'ERR: fixme: non-c4 hash in chain file, not implemented
ERR: fixme: non-c4 hash in chain file, not implemented'

Should:
? 

Anything to worry about?

**Comment by SiDu1860** [comment]
@OlliTee

**Comment by OlliTee** [comment]
@SiDu1860 the ARRIRAW HDE Transcoder tool didn‘t comply to the ASCMHL specification 1.0 section 7.4.2, which defines ’c4’ to be a required element. This has been fixed, so this issue can be closed.
