### ISSUE TITLE
Folder struct of scenarios

### ISSUE THREAD

**Issue by OlliTee** [ascmitc/mhl#137]
I noticed that for all examples/scenarios, you assume to have the clips located in a subdirectory of the reel, e.g. /A001R2EC/Clips/A002C006_141024_R2EC.mov.
At least for an ARRI camera, this Clips directory will not exist on the media, so the above example actually would like this:
/A001R2EC/A002C006_141024_R2EC.mov

When an ascmhl is created, the structure would look like this:
/A001R2EC/A002C001_141024_R2EC.mov
/A001R2EC/A002C002_141024_R2EC.mov
…
/A001R2EC/A002C006_141024_R2EC.mov
/A001R2EC/ascmhl/0001_howisthisfilenamedanyway.mhl
/A001R2EC/ascmhl/ascmhl_chain.xml

**Comment by ptrpfn** [comment]
The folder and file structures in the examples are independent of any real camera format on purpose and should just illustrate _a_ camera card. 

The behavior implemented in the `ascmhl` command line tool (and specification) works with any folder and file structure, including the media of ARRI cameras.
