### ISSUE TITLE
XXHash clarifications with new incoming algorithms

### ISSUE THREAD

**Issue by MichaelHudgins** [ascmitc/mhl#24]
The xxHash project [https://github.com/Cyan4973/xxHash](url) has a new algorithm that is in development.  It may be worth be proactive before first release of the new mhl spec and tool to clarify what xxHash algorithm is being used so that newer xxHash algorithms may be added seamlessly in the future.

**Comment by ptrpfn** [comment]
Thanks for the heads-up! We'll include that new variant of XXH3 into the discussion in order to make sure that we have a way to easily extend the list of hash formats.

**Comment by ptrpfn** [comment]
(or we include it right away)

**Comment by ptrpfn** [comment]
Decided to include new flavor XXH3/XXH128 in meeting 10 Jun 2020.

**Comment by ptrpfn** [comment]
Is now issue #27 https://github.com/ascmitc/mhl/issues/27
