### ISSUE TITLE
All print statements should be refactored to call a common logger.

### ISSUE THREAD

**Issue by jwaggs** [ascmitc/mhl#3]
We should have a central logger class that can take some initial configuration upon cli invocation (for settings like verbosity)... and then all "print" statements should be routed through this central logger. That way, common checks like "if verbose: then print" can be wrapped into a single "log_verbose" function... which will discard the log message if it was not configured to be verbose. 

The click framework that we are using to build this cli has an extremely useful feature to "echo". My suggestion: create a Logger class that has a few different levels of verbosity predefined... such as log_verbose, log, log_error, and log_fatal... with fatal logs calling context.exit so that we don't have to manually handle return flows out of the cli for fatal errors.

**Comment by jwaggs** [comment]
I can build the logger.

**Comment by ptrpfn** [comment]
Implemented by @jwaggs , reviewed, merged into master branch.
