### ISSUE TITLE
Allow for mhl seal directory to be overridden.

### ISSUE THREAD

**Issue by jwaggs** [ascmitc/mhl#37]
A copy / paste of Brandon Bussinger's feedback:

In order to ensure completeness of an entire day, a DIT or Footage Manger may need to send a ‘manifest of manifests’ to another department to ensure completeness for the day.

-Do we have a methodology for doing this?
-This would need to live separate from the data, is there affordance to verify a directory against an MHL that is NOT in the root folder even if that is the default location?

**Comment by ptrpfn** [comment]
Moved to meeting agenda
