### ISSUE TITLE
Nesting issue when not using xxh64 as original hash type

### ISSUE THREAD

**Issue by error1k** [ascmitc/mhl#48]
Seeing an issue when nesting and the original hash was not xxh64. If I create the initial ASC-MHL (of a MAG) as either sha1, c4 or md5 and then attempt to nest a set of MAGs (replicating a transport drive), the nest command creates a new hash (as xxh64) and is unable to write the directories and reports.

Below is an example of creating a ascmhl with sha1, then attempting to nest that path. I am having to run as sudo.

> ehansen-13Pro-5:mhl erikhansen$ sudo ./ascmhl.py create -h sha1 -v /Volumes/RND_SSD_HASH/SOURCE/TIMES/TIMES_sha1/A131R3KN/
Password:
Sealing folder at path: /Volumes/RND_SSD_HASH/SOURCE/TIMES/TIMES_sha1/A131R3KN/ ...
  created original hash for     A131C001_190520_R3KN.mov  sha1: 58f59f0e318a9e83032c92a676c0363dfc0e1101
  created original hash for     A131C002_190520_R3KN.mov  sha1: 187517d61034c3f2a1c2e22b1636e9c1cfba416a
  created original hash for     A131C003_190520_R3KN.mov  sha1: acfd86edabbcdc90c3d6c401a21556896047a6a3
  created original hash for     A131C004_190520_R3KN.mov  sha1: cb0d91479397f6e3eb04c44877b8203e08683bbb
  created original hash for     A131C005_190520_R3KN.mov  sha1: 9b5290e726f426c60b6046cfd7176b99c644d765
  created original hash for     A131C006_190520_R3KN.mov  sha1: 4e74807b1ad96527a86da49dbdee3b6eb2f44289
  created original hash for     A131C007_190520_R3KN.mov  sha1: 8242e71c871f4c31e12416bdcc0d5b7e1e6bfa0f
  created original hash for     A131C008_190520_R3KN.mov  sha1: ac31895b4ea267722ed3b9ac7dfe9efea321c16d
  created original hash for     A131C009_190520_R3KN.mov  sha1: 343fbe629f579eb15d6612263a0b70fd96e299db
  created original hash for     A131C010_190520_R3KN.mov  sha1: f15e89ba66e0eb2e027acace41f2d7967e4f8046
  created original hash for     A131C011_190520_R3KN.mov  sha1: 0a47742fe6875a526a1e374dfc638295408275ab
  created original hash for     A131C012_190520_R3KN.mov  sha1: d1eeefc755c03c228604c84fb81b7807a441962b
  created original hash for     A131R3KN_AVID.ale  sha1: 371614e35f09d1329fd05337a821cdefc1c7866c
  created original hash for     A131R3KN_BIN.bin  sha1: 6d652fedc4f020b35c3fa626fb29c8be50ebc16c
  calculated root hash  sha1: ccafa14003c5ee775ec79f14d99ba7fa9828140c
Created new generation ascmhl/0001_A131R3KN_2020-12-07_162116.mhl
(env) ehansen-13Pro-5:mhl erikhansen$ sudo ./ascmhl.py create -v /Volumes/RND_SSD_HASH/SOURCE/TIMES/TIMES_sha1/
Sealing folder at path: /Volumes/RND_SSD_HASH/SOURCE/TIMES/TIMES_sha1/ ...
  created new hash for          A131R3KN/A131C001_190520_R3KN.mov  xxh64: 80d1a985f849af18
  created new hash for          A131R3KN/A131C002_190520_R3KN.mov  xxh64: 90b5ac255be2a862
  created new hash for          A131R3KN/A131C003_190520_R3KN.mov  xxh64: 9da529bf532560a5
  created new hash for          A131R3KN/A131C004_190520_R3KN.mov  xxh64: d172ffc496f3c9be
  created new hash for          A131R3KN/A131C005_190520_R3KN.mov  xxh64: 908c8ebd35f5a028
  created new hash for          A131R3KN/A131C006_190520_R3KN.mov  xxh64: 76d80b4330363ab9
  created new hash for          A131R3KN/A131C007_190520_R3KN.mov  xxh64: 602f0fe53df5d813
  created new hash for          A131R3KN/A131C008_190520_R3KN.mov  xxh64: 8ea3876be04262e2
  created new hash for          A131R3KN/A131C009_190520_R3KN.mov  xxh64: f7a37f3d5e2d947d
  created new hash for          A131R3KN/A131C010_190520_R3KN.mov  xxh64: df6f4ebb2d0142e8
  created new hash for          A131R3KN/A131C011_190520_R3KN.mov  xxh64: f53ee565a05777f3
  created new hash for          A131R3KN/A131C012_190520_R3KN.mov  xxh64: 98f0953054947a79
  created new hash for          A131R3KN/A131R3KN_AVID.ale  xxh64: 0fd86c33ffb1e2a3
  created new hash for          A131R3KN/A131R3KN_BIN.bin  xxh64: 21bd19e52e6a1ef5
  calculated directory hash for A131R3KN  xxh64: 42f43d97b8f7effb
  calculated root hash  xxh64: f7c6f2e56a7ce9c3
Traceback (most recent call last):
  File "/Users/erikhansen/ASCMHL/mhl/./ascmhl.py", line 37, in <module>
    mhltool_cli()
  File "/Users/erikhansen/ASCMHL/mhl/env/lib/python3.9/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/erikhansen/ASCMHL/mhl/env/lib/python3.9/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/erikhansen/ASCMHL/mhl/env/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/erikhansen/ASCMHL/mhl/env/lib/python3.9/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/erikhansen/ASCMHL/mhl/env/lib/python3.9/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/erikhansen/ASCMHL/mhl/mhl/commands.py", line 55, in create
    create_for_folder_subcommand(root_path, verbose, hash_format, no_directory_hashes, single_file)
  File "/Users/erikhansen/ASCMHL/mhl/mhl/commands.py", line 114, in create_for_folder_subcommand
    commit_session(session)
  File "/Users/erikhansen/ASCMHL/mhl/mhl/commands.py", line 482, in commit_session
    session.commit(creator_info)
  File "/Users/erikhansen/ASCMHL/mhl/mhl/generator.py", line 132, in commit
    history.write_new_generation(new_hash_list)
  File "/Users/erikhansen/ASCMHL/mhl/mhl/history.py", line 252, in write_new_generation
    self._validate_new_hash_list(new_hash_list)
  File "/Users/erikhansen/ASCMHL/mhl/mhl/history.py", line 280, in _validate_new_hash_list
    raise AssertionError('no hash entry found for new hash', hash_entry)
AssertionError: ('no hash entry found for new hash', <mhl.hashlist.MHLHashEntry object at 0x10d4df340>)

**Comment by jwaggs** [comment]
@error1k thanks for posting this - good find and is certainly a bug. I'll tag this for the next alpha release (which is currently set for Jan. 20, 2021). Hopefully we can resolve this by then. 

This issue blocks #46

**Comment by ptrpfn** [comment]
Bug is reproduced, reason is found, fix is on the way. We need a bit more testing, might be committed (together with a new test case) tomorrow. 
@error1k : Thank you for reporting that one!

**Comment by ptrpfn** [comment]
Bug should be fixed with the merged fix. @error1k can you confirm that?

**Comment by ptrpfn** [comment]
Reopening for final confirm.

**Comment by error1k** [comment]
Fix looks good. Moving on to additional testing.
