### ISSUE TITLE
Needs documentation

### ISSUE THREAD

**Issue by jwaggs** [ascmitc/mhl#5]
For the most part, I can follow a significant amount of the code with minimal effort since many of the functions are only 4 or 5 lines long. Your functions are also named well. In those situations, I can obviously infer the scope of encapsulation and therefor the necessity of commenting becomes debatable.

But when there is a ~300 line class like the `HashListCreator` ... it becomes very difficult to follow along without a top level comment to explain the goal and purpose of the code at hand. Currently I have to infer the goal from the implementation rather than reading a goal in a comment and then clearly seeing how the implementation achieves that goal. 

I'm not trying to be critical here, just making sure I clearly summarize the "issue" at hand. I won't suggest that everything needs to be commented because I don't even do that myself... But it sure would be helpful when functions are more than 5-10 lines long. Also, to be fair, I'm aware that the comments in the Hive repo were lacking too. I will ensure that I document better moving forward as well.

If you could wrap back around and merely document a quick sentence or two for each class and large function, that would be super useful for me. Thanks!

**Comment by ptrpfn** [comment]
Got it. I will look through the longer classes/methods/functions and add a bit of comment to better illustrate goal and purpose asap.

**Comment by ptrpfn** [comment]
Added docstrings in branch doc-improvements

**Comment by jwaggs** [comment]
Thanks this should be good for now.
