### ISSUE TITLE
Decide how to store directory hash pairs in ASCMHL XML files

### ISSUE THREAD

**Issue by ptrpfn** [ascmitc/mhl#56]
## Currently implemented "quick" solution (in PR #51 )

* Extension of the existing `<hash>` elements and their hashformat children (`<md5>`, `<c4>`, ..) with attribute `structure`

Example:

```
    <hash directory="true">
      <path lastmodificationdate="2020-01-15T13:00:00+00:00">Clips</path>
      <xxh64 structure="a27e08b77ae22c78">6d43a82e7a5d40f6</xxh64>
    </hash>
```

* Pros: 
	* simple extension in xsd: only one new attribute
* Cons:
	* not very clean/obvious solution

## Alternative solution A (TBD)

* Hash pairs are set of new elements

Example:

```
    <hash directory="true">
      <path lastmodificationdate="2020-01-15T13:00:00+00:00">Clips</path>
      <xxh64>
      	<content>6d43a82e7a5d40f6</content>
      	<structure>a27e08b77ae22c78</structure>
      </xxh64>
    </hash>
```

* Pros: 
	* better understandable solution
* Cons:
	* larger extension of xsd: hash format type changes and now has two variants: one with the hash as direct content (as is) and one with two child elements for `<content>` and `<structure>`.

**Comment by fschleich** [comment]
### Alternative solution B

- use separate element type for directory hashes, as outlined in example:

```
<directoryhash>
    <path lastmodificationdate="2020-01-15T13:00:00+00:00">Clips</path>
    <content>
        <xxh64>6d43a82e7a5d40f6</xxh64>
    </content>
    <structure>
        <xxh64>a27e08b77ae22c78</xxh64>
    </structure>
</directoryhash>
```

- Pros:
-- no overhead to file hashes
-- even better understandable solution
-- able to reuse hash type definitions (xxh64, md5, c4, etc)
- Cons:
-- additional type definition in xsd

**Comment by ptrpfn** [comment]
"Alternative solution B" sounds good to me.

I added an first XSD (commit [cd1f149b](https://github.com/ascmitc/mhl/commit/cd1f149baa7d56c8f3d69c6deb8e5fc5c48ced62) ) for that option for review in branch [dev/split-directory-hashes-xsd](https://github.com/ascmitc/mhl/tree/dev/split-directory-hashes-xsd). 

When checking out that branch you can test the validity of example MHL file (example attached) with 

```
% ./ascmhl.py xsd-schema-check path/to/0001_A002R2EC_2021-01-27_092931.mhl
```

[0001_A002R2EC_2021-01-27_092931.mhl.zip](https://github.com/ascmitc/mhl/files/5918548/0001_A002R2EC_2021-01-27_092931.mhl.zip)

**Comment by jwaggs** [comment]
@ptrpfn do you feel its appropriate to update this thread with our further discussions on this topic yet? I'll leave it to you to summarize the status of this proposal if you don't mind.

**Comment by ptrpfn** [comment]
As soon as we merged PR https://github.com/ascmitc/mhl/pull/51 (which to my knowledge represents the decided solution for directory hashes via the group discussions), we can take a look at this small remaining topic of how to store them syntactically. 
The solution in PR #51 is still the simple one with the "structure" attribute: `<xxh64 structure="80e491fb8b96fd82">6d43a82e7a5d40f6</xxh64>`. 
Some additional changes would be required for implementing option B (see above). These should probably be done after PR #51 is merged.

**Comment by ptrpfn** [comment]
Done and implemented.
