### ISSUE TITLE
Official package name decision

### ISSUE THREAD

**Issue by cbenhagen** [ascmitc/mhl#70]
Before publishing the package to the Python Package Index (PyPI) an official decision on the name should be made. `mhl`, `ascmhl` or `mhllib` are available.

**Comment by jwaggs** [comment]
@ptrpfn did we officially decide on using `ascmhl`? I remember the group leaned that way. But it seems excessive to have a six character acronym as the name. Thats a lot of characters that can't be pronounced for people to remember as a command name.

I won't put up a fight on it if we stick with `ascmhl` - but I also could make a case for publishing this as MHL version 2.

Thoughts @ptrpfn?

**Comment by cbenhagen** [comment]
The package name (as in `pip install mhl`) does not have to be the same as the cli tool or the module name (`from mhl import foo`). I would prefer to go with `mhl` for all 3 of them for simplicity.

**Comment by ptrpfn** [comment]
I remember the group discussions about prefixing everything with "ASC" (like in ASC CDL). Reasons have been to distinguish properly from the previous version of MHL (which is called "mhl"), and to be in line with the ASC's naming convention (which provides the context for this work). For example, the cli tool already has been renamed to `ascmhl` previously. 
So I would propose to put the question of naming on the list for the next meeting for a quick discussion how we should proceed.  From what I read above we're talking about 

- the names of the cli tool (`$ XXX verify -v /path/to/folder`), 
- the package name (as in `pip install XXX`), and 
- the module name (`from XXX import foo`) in Python.

**Comment by cbenhagen** [comment]
We decided to use `ascmhl` for all three.
