### ISSUE TITLE
Publish package to the Python Package Index (PyPI)

### ISSUE THREAD

**Issue by cbenhagen** [ascmitc/mhl#71]
This depends on #70

As discussed in #63 this could be done automatically on new git tags extending the already used GitHub Actions making sure the new version passes all unit and integration tests.

**Comment by jwaggs** [comment]
Hey @cbenhagen and @ptrpfn sorry for the delay on responses the past few PRs / issues. Hoping to address these issues in greater detail prior to our meeting this Wednesday - I'll get back with you shortly.

**Comment by jwaggs** [comment]
I agree we should utilize tagging to automatically publish after testing succeeds. @cbenhagen let's discuss getting this package published once we resolve #70 as you mentioned. We could get a dry run up on TestPyPi soon.

My apologies on the delay in progress this past week. Co-worker is moving on to a new company so my work load has doubled to accommodate for the time being. MHL had to take a quick back seat. 

@cbenhagen - you should consider joining our bi-weekly video chats. There is one coming up this Wednesday. @ptrpfn or I can get you info if you need it.

**Comment by cbenhagen** [comment]
Sure I'd be happy to join.

**Comment by jwaggs** [comment]
@cbenhagen you should have an email invite to the `ascmhl` slack channel. I sent it to your github listed email - lmk if you need it sent to another. 

Patrick posts the meeting info & links in slack.
