### ISSUE TITLE
Use Black formatter for consistent code formatting 

### ISSUE THREAD

**Issue by cbenhagen** [ascmitc/mhl#75]
I'd like to propose the use of the [Black code formatter](https://github.com/psf/black). This helps a lot to have a consistent formatting style. It is used by many popular Python projects for the sake of not having to discuss formatting ever again.

While it is opinionated and does not provide many config options by design, one thing we would need to decide on is the line length. An old and endlessly discussed topic. Python once specified a length of 72 characters in their PEP 8 style guide. The currently enforced max line length by the linter in the CI pipeline is set to 127 characters. PyCharm uses 120 characters by default so this is what I would often use in projects but I would be fine with either number. What are your opinions on this?

Once decided on using Black, the style can be enforced using a GitHub Action. I already prepared a PR for that.

**Comment by jwaggs** [comment]
@cbenhagen I think this is a great suggestion. Feel free to open a PR.

**Comment by jwaggs** [comment]
as for line length - i always prefer longer line lengths - 120+ would be my personal preference. 

However this is a topic I'm not heavily opinionated in. Any opinion @ptrpfn?

**Comment by cbenhagen** [comment]
Currently there is a mix of double and single quotes for strings. While I personally lean a bit more to single quoted strings, Black has no option to enforce them. Skipping normalization can be configured, but that would leave us with the current state of mixed usage. Because it's easier to type, I would often type the single quotes and just let black handle the conversion. There are Black plugins for many IDEs. Also we could add a pre-commit hook or a GitHub action to automatically format code instead of only checking.
