### ISSUE TITLE
CLI command / argument / option design

### ISSUE THREAD

**Issue by jwaggs** [ascmitc/mhl#8]
Commands:

Currently, there are two main commands... verify and read. Are there any other commands that are planned or that have been discussed ? Do we want to keep the initial seal as an implicit part of the first verification or require it to be explicitly sealed with a different command the first time? Any other related command design worth discussing at this point?

Arguments:

- Would we like to default to the current working directory if the root_path argument isn't provided? Currently we explicitly require the folder path to be provided explicitly. 

Options:

- Since we already allow the name to be set with a cli option, would it make more sense for us to remove username as an option entirely and always grab the system username instead?

- Is there any objection to changing the default to include directory hashes? If not, the flag would be more appropriate as `files_only` with the default set as false.

**Comment by ptrpfn** [comment]
There is also the need to clean this up. Right now there are several orphaned options and commands half-implemented that are not needed any more.

**Comment by ptrpfn** [comment]
@jwaggs Can we close this topic with the latest command spec?

**Comment by jwaggs** [comment]
@ptrpfn would you mind posting the command spec here for history sake before we close it out?

**Comment by ptrpfn** [comment]
_Here is the spec:_

# Running `mhl-tool.py`

The asc-mhl toll can be used to work with 

* entire file hierarchies (commands `seal`, `check`, and `diff`), 
* asc-mhl history folders (command `info`), 
* and on single files or lists of files (commands `record`, `verify` and `history`).

## Working with file hierarchies

The most common commands when using the `mhl-too.py` in data management scenarios are the `seal` and the `check` commands. 

Sealing a folder / drive with the `seal` command traverses through a folder hierarchy, hashes all found files and compares ("verifies") the hashes against the records in the `asc-mhl` folder (if present). The command creates a new generation (or an initial one) for the content of an entire folder at the given folder level. It can be used to document all files in a folder or drive with all verified or newly created file hashes of the moment the `seal` command ran.

Checking a folder / drive with the `check` command traverses through the content of a folder, hashes all found files and compares ("verifies") the hashes against the records in the `asc-mhl` folder. The `check` command behaves like a `seal` command, but doesn't write new generations. It can be used to verify the content of a received drive with existing asc-mhl information.

The `diff` command also traverses through the content of a folder / drive.  The `diff` command thus behaves like the `check` command, but the `diff` command does not hash any files (e.g. doesn't do file verification) and thus is much faster in execution. It can be used to print all files that are existent in the file system and are not registered in the `asc-mhl` folder yet, and all files that are registered in the `asc-mhl` folder but that are missing in the file system.


### The `seal` command 

The `seal` command traverses through a folder hierarchy (such as a folder with media files, a camera card, or an entire drive). The command hashes all files  and the hashes are compared against records in the `asc-mhl` folder.

The command detects, prints error, and exits with a non-0 exit code if it finds files that are registered in the `asc-mhl` folder but that are missing in the file system. 

Files that are existent in the file system but are not registered in the `asc-mhl` folder yet, are registered as new entries in the newly created generation(s).

The `seal` command takes the root folder of the file hierarchy as the parameter:

```
$ mhl seal /path/to/folder/
```

It works on folders with or without an `asc-mhl` folder within the given folder hierarchy, and creates a new `asc-mhl` folder at the given folder level if none is present before.

`asc-mhl` folders further down the file hierarchy are read, handled, and referenced in top-level `asc-mhl` folders. Existing `asc-mhl` folders further down the folder structure will also get a new generation added.

Implementation:

* _read (recursive) mhl history (mhllib)_
* _traverse folder_
 	* _hash each file_
	* _if `asc-mhl` folder exists, compare ("verify") hash (mhllib)_
	* _on error (including mismatching hashes):_
		* _print error_
	 	* _continue_
 	* _add files to new generation if not present yet_
* _compare found files in file system with records in asc-mhl folder and warn if files are missing that are recorded in the asc-mhl folder_
* _create new generation(s) (mhllib)_


### The `check` command 

The `check` command traverses through the content of a folder, hashes all found files and compares ("verifies") the hashes against the records in the `asc-mhl` folder.

The command detects, prints errors, and exits with a non-0 exit code for

* all files that are existent in the file system but are not registered in the `asc-mhl` folder yet, and
* all files that are registered in the `asc-mhl` folder but that are missing in the file system. 

It is run with the root folder of the file hierarchy as the parameter.

```
$ mhl check /path/to/folder/
```

If no `asc-mhl` folder is found on the root level, an error is thrown.

`asc-mhl` folders further down the file hierarchy are also read, and its recorded hashes are used for verification.

Implementation:

* _error if no mhl folder found on root level_
* _read (recursive) mhl history (mhllib)_
* _traverse folder_
	* _hash each file_
	* _compare ("verify") hash (mhllib)_
	* _on error (including mismatching hashes):_
		* _print error_
	 	* _continue_
* _compare found files in file system with records in asc-mhl folder and warn if files are missing that are recorded in the asc-mhl folder_
* _end with exit !=0 if at least one of the files has failed, a file was missing, or new files have been found_


### The `diff` command 

The `diff` command is very similar to the `check` command, only that it doesn't create hashes and doesn't verify them. It can be used to quickly check if a folder structure has new files that have not been recorded yet, or if files are missing.

The command detects, prints errors, and exits with a non-0 exit code for

* all files that existent in the file system but not registered in the `asc-mhl` folder yet, and
* all files that are registered in the `asc-mhl` folder but that are missing in the file system. 

It is run with the root folder of the file hierarchy as the parameter.

```
$ mhl diff /path/to/folder/ 
```

If no `asc-mhl` folder is found on the root level, an error is thrown.

`asc-mhl` folders are read recursively. 

Implementation:

* _error if no mhl folder found on root level_
* _read (recursive) mhl history (mhllib)_
* _traverse folder_
	* _on missing file:_
		* _print error_
	 	* _continue_
* _compare found files in file system with records in asc-mhl folder and warn if files are missing that are recorded in the asc-mhl folder_
* _end with exit !=0 if at least one of the files has failed, a file was missing, or new files have been found_



## Working with a `asc-mhl` folder

The `asc-mhl` folder contains well readable XML files, but the number of recorded files, generations, hash entries, verification info and so forth adds up to an amount of information that cannot be quickly understood. 

The `info` command helps to get a quick overview of the contents of the stored information in an `asc-mhl` folder. 


### The `info` command 

The `info` command can print

* a summary (with the `-s` option) of the information in an asc-mhl folder, such as number of recorded files, and a list of the generations with their creator info, and/or
* a list (with the `-l` option) of all file (and folder) records stored in an asc-mhl folder, together with relative file paths, file size, and known file hashes.

It is run with the path to a specific `asc-mhl`folder.

```
$ mhl info [-s|-l] /path/to/asc-mhl/ 
```

Implementation:

* _error if no mhl folder found on root level_
* _read (recursive) mhl history (mhllib)_
* _if summary option:_
	* _print summary_
* _if list option:_
	* _for each file record_
		* _print file info, hashes, etc._



## Working with single files

In some scenarios "sealing" and "checking" entire folder structures is not sufficient enough, and finer control of the processes files is needed. 

For that the `record`, `verify`, and `history` commands are used.

Recording single files in a new generation with the `record` command allows to add single files to an existing folder structure and create new generations only with records of these files.

Hashing and verifying single files against hash information stored in the `asc-mhl` folder  allows to "check" single files without the need for a (probably much longer running) check of the integrity of the entire folder structure. 

The `history` command prints the known history of a single file with details about all generations.


### The `record` command

The `record` command can be used to create a new generation in the mhl-history. This can be used for instance when adding single files to an already mhl-managed file hierarchy. It is run with either 

* the path to a single file, or
* a text file with paths to multiple files

as the parameter.

```
$ mhl record /path/to/single/file
$ mhl record -l list/of/files.txt
```

The command looks for an `asc-mhl` folder in the folders above the given files. A new generation is created in all relevant `asc-mhl` folders (e.g. in a nested mhl-history).

If no mhl-history is present yet, an error is thrown.

You can also specify the folder level where to create a new `asc-mhl` folder:

```
$ mhl record -r /path/to/asc-mhl /path/to/single/file 
$ mhl record -r /path/to/asc-mhl -l list/of/files.txt
```

The path to the `asc-mhl` folder needs to be "above" the specified file(s).

If used with the `-l` option, all files in the list must be contained in the same (recursive) mhl-history. 

Implementation:

* _find mhl-history information in the path above (mhllib)_
* _read (recursive) mhl-history (mhllib)_
* _OR_
* _create new `asc-mhl` folder at given path_
* _for each file from input_
	* _check if file is not recorded in `asc-mhl` folder yet_
	* _hash file_
	* _add record for file to new generation (mhllib)_
		* _add new generation if necessary in appropriate `asc-mhl` folder (mhllib)_


### The `verify` command

The `verify` command can be used to verify a single or multiple files. It is run with either 

* the path to a single file, or
* a text file with paths to multiple files

as the parameter.

```
$ mhl verify /path/to/single/file
$ mhl verify -l list/of/files.txt
```

The command looks for an `asc-mhl` folder in the folders above the given files. If no mhl-history is present yet, an error is thrown.

If used with the `-l` option, all files in the list must be contained in the same (recursive) mhl-history. 

Implementation:

* _if input is `-f`: create a list of files from input_
* _find mhl-history information in the path above (mhllib)_
	* _error of no `asc-mhl` folder is found_
* _read (recursive) mhl-history (mhllib)_
* _for each file from input_
	* _hash each file_
	* _compare hashes (mhllib)_ 
* _if file is not found in mhl-history, throw error_
* _on error (including mismatching hashes):_
	* _don't break_
	* _print error_
	* _end with exit !=0 if at least one of the files has failed_


### The `history` command

The `history` command can be used to output information about the full and detailed history information about one file.

```
$ mhl history /path/to/file
```

The command outputs each generation where the file has been handled, including date, creator info, activity, hash, and absolute path.

Implementation:

* _find mhl-history information in the path above (mhllib)_
	* _error of no `asc-mhl` folder is found_
* _print detailed info for file_
