### ISSUE TITLE
Classes should refer to context for configurable information

### ISSUE THREAD

**Issue by jwaggs** [ascmitc/mhl#9]
During my refactor in PR #7, the new code that I wrote utilizes the context that I built. But I have not refactored the classes in the src/mhl directory to refer to the context for this data yet (mainly due to time constraints). This means that some of the root configurations are set it multiple places and passed down as each object creates other objects. 

Now that this data has been stored on a root context, the main mhl classes should be refactored to reference the root context when they need settings information rather than storing it on themselves as well.

**Comment by ptrpfn** [comment]
The verbose property is also something that should be stored centrally.

**Comment by ptrpfn** [comment]
The verbose property is also something that should be stored centrally.

**Comment by jwaggs** [comment]
The structure of the code has changed since this issue and this is no longer necessary.

**Comment by ptrpfn** [comment]
Referred to old implementation, closing.
